# Generated by Django 4.0.4 on 2022-04-30 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=100, unique=True, verbose_name='author name')),
            ],
            options={
                'order_with_respect_to': 'authorName',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=100)),
                ('edition', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'order_with_respect_to': 'branchName',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelID', models.CharField(max_length=2, unique=True)),
                ('hostelName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditionofbook', models.IntegerField(choices=[(1, 'Bad'), (2, 'Ok'), (3, 'Good'), (4, 'New')], default=1)),
                ('price', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.book')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('phoneNumber', models.BigIntegerField()),
                ('bitsID', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('roomNumber', models.IntegerField()),
                ('wallet', models.IntegerField(default=1000)),
                ('hostelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hostel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('buyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=10, unique=True)),
                ('courseName', models.CharField(max_length=100, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch')),
            ],
            options={
                'order_with_respect_to': 'branch',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='belongstocourse',
            field=models.ManyToManyField(to='base.course'),
        ),
        migrations.AddField(
            model_name='book',
            name='writtenby',
            field=models.ManyToManyField(to='base.author'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'user',
            },
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(unique=True, upload_to='productpics/')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
            options={
                'unique_together': {('productID', 'photo')},
            },
        ),
    ]
