# Generated by Django 4.0.4 on 2022-04-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=100),
        ),
    ]
