# Generated by Django 4.0.4 on 2022-04-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_branch_course_author'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='branch',
            order_with_respect_to='branchName',
        ),
        migrations.AlterOrderWithRespectTo(
            name='course',
            order_with_respect_to='branch',
        ),
    ]
