# Generated by Django 4.0.4 on 2022-04-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_branch_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=100)),
                ('edition', models.IntegerField()),
            ],
        ),
    ]
