# Generated by Django 4.0.4 on 2022-04-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_writtenby_belongstocourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='writtenby',
            unique_together={('bookID', 'authorID')},
        ),
    ]
