# Generated by Django 4.0.4 on 2022-04-13 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_alter_writtenby_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostelID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('hostelName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditionofbook', models.IntegerField(choices=[(1, 'Bad'), (2, 'Ok'), (3, 'Good'), (4, 'New')], default=1)),
                ('price', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.book')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('phoneNumber', models.BigIntegerField()),
                ('bitsID', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('roomNumber', models.IntegerField()),
                ('hostelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hostel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='belongstocourse',
            unique_together={('bookID', 'courseID')},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('buyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
            options={
                'unique_together': {('productID', 'photo')},
            },
        ),
    ]
