# Generated by Django 4.0.4 on 2022-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_hostel_product_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='writtenby',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='writtenby',
            name='authorID',
        ),
        migrations.RemoveField(
            model_name='writtenby',
            name='bookID',
        ),
        migrations.AddField(
            model_name='book',
            name='belongstocourse',
            field=models.ManyToManyField(to='base.course'),
        ),
        migrations.AddField(
            model_name='book',
            name='writtenby',
            field=models.ManyToManyField(to='base.author'),
        ),
        migrations.DeleteModel(
            name='BelongsToCourse',
        ),
        migrations.DeleteModel(
            name='WrittenBy',
        ),
    ]
