# Generated by Django 4.0.4 on 2022-04-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_writtenby_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphotos',
            name='photo',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
