# Generated by Django 4.0.4 on 2022-04-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_productphotos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphotos',
            name='photo',
            field=models.ImageField(unique=True, upload_to='productpics/'),
        ),
    ]
